spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: caesar
    password: 164375
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8023
  ssl:
    key-store: classpath:caelog.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: caelog
    trust-store: classpath:caelog.jks
    trust-store-password: 123456
    client-auth: want

